// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhPqZtbqLteVA4g4OrH4Zwhd7tGy6vx6s',
    appId: '1:938184380478:web:319da3a871edb6b7fa016f',
    messagingSenderId: '938184380478',
    projectId: 'campuscloset-ef092',
    authDomain: 'campuscloset-ef092.firebaseapp.com',
    storageBucket: 'campuscloset-ef092.firebasestorage.app',
    measurementId: 'G-XP20PN9W51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASZFDpBZKlddrMr8AEaa-UG21dwEqm0X4',
    appId: '1:938184380478:android:b8e451fe7a5675e3fa016f',
    messagingSenderId: '938184380478',
    projectId: 'campuscloset-ef092',
    storageBucket: 'campuscloset-ef092.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD24K7vk71_3gLCm0Xu4AOTcdx5Nm7Kguo',
    appId: '1:938184380478:ios:5705350c54406918fa016f',
    messagingSenderId: '938184380478',
    projectId: 'campuscloset-ef092',
    storageBucket: 'campuscloset-ef092.firebasestorage.app',
    iosClientId: '938184380478-sfeki58dcppq8q9ks0pkaitkq8fsok78.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterP1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD24K7vk71_3gLCm0Xu4AOTcdx5Nm7Kguo',
    appId: '1:938184380478:ios:5705350c54406918fa016f',
    messagingSenderId: '938184380478',
    projectId: 'campuscloset-ef092',
    storageBucket: 'campuscloset-ef092.firebasestorage.app',
    iosClientId: '938184380478-sfeki58dcppq8q9ks0pkaitkq8fsok78.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterP1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhPqZtbqLteVA4g4OrH4Zwhd7tGy6vx6s',
    appId: '1:938184380478:web:bbbe14b24cee3114fa016f',
    messagingSenderId: '938184380478',
    projectId: 'campuscloset-ef092',
    authDomain: 'campuscloset-ef092.firebaseapp.com',
    storageBucket: 'campuscloset-ef092.firebasestorage.app',
    measurementId: 'G-RHRFGV733H',
  );
}
